import {
  AirportInfo,
  AirspaceStatus,
  NewsItem,
  AirlineInfo,
  EmergencyNumber,
  EmbassyContact,
  VerifiedSource,
} from "./types";

// ─── Airport & Airspace Status ───
export const airspaceStatus: AirspaceStatus = "closed";

export const airports: AirportInfo[] = [
  {
    id: "dxb",
    name: "Dubai International Airport",
    code: "DXB",
    subtitle: "Terminal 1, 2 & 3 · Al Garhoud, Dubai",
    status: "limited",
    statusLabel: "LIMITED OPS",
    description:
      "Limited repatriation flights only. Do NOT travel to the airport unless your airline has directly confirmed your departure time and seat. Priority given to earlier bookings.",
  },
  {
    id: "dwc",
    name: "Dubai World Central – Al Maktoum International",
    code: "DWC",
    subtitle: "Jebel Ali · Dubai South",
    status: "limited",
    statusLabel: "LIMITED OPS",
    description:
      "Limited operations resumed from 2 March. Do NOT travel unless airline has confirmed your flight. Check which terminal your flight departs from.",
  },
  {
    id: "auh",
    name: "Abu Dhabi International Airport",
    code: "AUH",
    subtitle: "Abu Dhabi · Zayed City",
    status: "partial",
    statusLabel: "PARTIAL",
    description:
      "Partial resumption underway for select repatriation flights. Etihad commercial flights suspended until 2 PM, 4 March. Check airline before heading out.",
  },
  {
    id: "shj",
    name: "Sharjah International Airport",
    code: "SHJ",
    subtitle: "Sharjah · Home of Air Arabia",
    status: "limited",
    statusLabel: "LIMITED OPS",
    description:
      "Limited resumption announced by Sharjah Airport Authority from 2 March. Contact your airline before travelling.",
  },
];

export const airspaceInfo: AirportInfo = {
  id: "airspace",
  name: "UAE Airspace",
  code: "UAE",
  subtitle: "GCAA – General Civil Aviation Authority",
  status: "closed",
  statusLabel: "RESTRICTED",
  description:
    "Partial airspace reopening under phased, airline-managed restart. GCAA authorised 'exceptional' operations only. Not fully open — restricted routes only.",
};

// ─── News Feed ───
export const newsItems: NewsItem[] = [
  {
    id: "n1",
    tag: "latest",
    source: "Euronews",
    title: "Limited flights resume — but 80%+ still cancelled",
    body: "Several carriers cautiously resumed a small number of flights from UAE on 2–3 March, offering some relief. However, more than 80% of DXB flights and over half of AUH flights remain cancelled per FlightAware. Dubai government: only go to airport if directly contacted.",
    sourceUrl: "https://www.euronews.com",
    timestamp: "2026-03-03T15:19:00+04:00",
    verified: true,
  },
  {
    id: "n2",
    tag: "airlines",
    source: "The National",
    title: "flydubai resumes limited ops from T2 & T3 as of 3 PM today",
    body: "As of 3 PM on 3 March, flydubai confirmed limited flights operating from Terminals 2 and 3 at DXB. The airline is prioritising disrupted passengers and says it is working to ramp up operations once temporary restrictions are lifted. Situation remains dynamic.",
    sourceUrl: "https://www.thenationalnews.com",
    timestamp: "2026-03-03T15:00:00+04:00",
    verified: true,
  },
  {
    id: "n3",
    tag: "airlines",
    source: "Gulf News",
    title: "Emirates announces phased restart from Terminal 3",
    body: "Emirates has begun a phased restart of limited flights from DXB Terminal 3. The airline is contacting affected passengers directly for rebooking. Do not travel to the airport without confirmation from the airline.",
    sourceUrl: "https://www.gulfnews.com",
    timestamp: "2026-03-03T14:30:00+04:00",
    verified: true,
  },
  {
    id: "n4",
    tag: "government",
    source: "WAM",
    title: "UAE government extends automatic visa extensions for stranded travelers",
    body: "The UAE government has announced automatic visa extensions for all travelers stranded due to the airspace restrictions. No action is required from affected travelers. The extension covers all visa types and will remain in effect until normal operations resume.",
    sourceUrl: "https://www.wam.ae",
    timestamp: "2026-03-03T13:00:00+04:00",
    verified: true,
  },
  {
    id: "n5",
    tag: "airports",
    source: "Dubai Airports",
    title: "DXB activates passenger welfare across all terminals",
    body: "Dubai Airports has activated comprehensive passenger welfare services at DXB Terminals 1, 2, and 3. Free Wi-Fi, charging stations, blankets, and meal vouchers are being distributed. Medical assistance is available at all terminal medical centers.",
    sourceUrl: "https://www.dubaiairports.ae",
    timestamp: "2026-03-03T11:00:00+04:00",
    verified: true,
  },
  {
    id: "n6",
    tag: "advisory",
    source: "GCAA",
    title: "GCAA: Airspace remains restricted — phased airline restart authorised",
    body: "The UAE General Civil Aviation Authority confirms airspace remains under restricted operations. A phased, airline-managed restart has been authorised for exceptional flights only. Full commercial services have not resumed. Passengers must wait for direct airline confirmation.",
    sourceUrl: "https://www.gcaa.gov.ae",
    timestamp: "2026-03-03T10:00:00+04:00",
    verified: true,
  },
  {
    id: "n7",
    tag: "airlines",
    source: "Al Jazeera",
    title: "Etihad suspends commercial flights until 4 March afternoon",
    body: "Etihad Airways has announced all commercial flights from Abu Dhabi International Airport remain suspended until at least 2 PM on 4 March. Select repatriation flights may operate. Passengers advised to check Etihad's website for the latest status.",
    sourceUrl: "https://www.aljazeera.com",
    timestamp: "2026-03-03T09:30:00+04:00",
    verified: true,
  },
  {
    id: "n8",
    tag: "latest",
    source: "CNBC",
    title: "Regional airspace tensions ease but full reopening not expected for days",
    body: "Analysts indicate that while regional tensions have de-escalated slightly, a full reopening of UAE airspace is not expected for several days. Airlines are operating on a day-by-day basis with extremely limited schedules.",
    sourceUrl: "https://www.cnbc.com",
    timestamp: "2026-03-03T08:00:00+04:00",
    verified: true,
  },
];

// ─── Airlines ───
export const airlines: AirlineInfo[] = [
  {
    id: "emirates",
    name: "Emirates",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "600 555555",
    whatsapp: "+971 50 123 4567",
    websiteUrl: "https://www.emirates.com",
    notes: "",
  },
  {
    id: "flydubai",
    name: "flydubai",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "600 54 44 45",
    whatsapp: "+971 600 54 44 45",
    websiteUrl: "https://www.flydubai.com",
    notes: "",
  },
  {
    id: "etihad",
    name: "Etihad Airways",
    hub: "AUH",
    status: "operating",
    statusLabel: "",
    phone: "800 2324",
    whatsapp: "+971 2 599 0000",
    websiteUrl: "https://www.etihad.com",
    notes: "",
  },
  {
    id: "airarabia",
    name: "Air Arabia",
    hub: "SHJ",
    status: "operating",
    statusLabel: "",
    phone: "+971 600 508001",
    whatsapp: "+971 600 508001",
    websiteUrl: "https://www.airarabia.com",
    notes: "",
  },
  {
    id: "qatarairways",
    name: "Qatar Airways",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 600 521473",
    whatsapp: "+974 4449 6000",
    websiteUrl: "https://www.qatarairways.com",
    notes: "",
  },
  {
    id: "turkish",
    name: "Turkish Airlines",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "800 0357 04313",
    websiteUrl: "https://www.turkishairlines.com",
    notes: "",
  },
  {
    id: "ba",
    name: "British Airways",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "800 0441 2679",
    websiteUrl: "https://www.britishairways.com",
    notes: "",
  },
  {
    id: "lufthansa",
    name: "Lufthansa",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 373 9100",
    websiteUrl: "https://www.lufthansa.com",
    notes: "",
  },
  {
    id: "airfrance",
    name: "Air France",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 602 5411",
    whatsapp: "800 23 823",
    websiteUrl: "https://www.airfrance.ae",
    notes: "",
  },
  {
    id: "gulfair",
    name: "Gulf Air",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 331 4111",
    websiteUrl: "https://www.gulfair.com",
    notes: "",
  },
  {
    id: "saudia",
    name: "Saudia",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "800 844 2000",
    websiteUrl: "https://www.saudia.com",
    notes: "",
  },
  {
    id: "flynas",
    name: "flynas",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 266 0444",
    websiteUrl: "https://www.flynas.com",
    notes: "",
  },
  {
    id: "egyptair",
    name: "EgyptAir",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 230 6666",
    websiteUrl: "https://www.egyptair.com",
    notes: "",
  },
  {
    id: "ethiopian",
    name: "Ethiopian Airlines",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "8000 320 372",
    websiteUrl: "https://www.ethiopianairlines.com",
    notes: "",
  },
  {
    id: "kenyaairways",
    name: "Kenya Airways",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 229 2000",
    websiteUrl: "https://www.kenya-airways.com",
    notes: "",
  },
  {
    id: "airindia",
    name: "Air India",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 227 6787",
    whatsapp: "+91 96670 34444",
    websiteUrl: "https://www.airindia.com",
    notes: "",
  },
  {
    id: "indigo",
    name: "IndiGo",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 321 6900",
    whatsapp: "+91 70651 45858",
    websiteUrl: "https://www.goindigo.in",
    notes: "",
  },
  {
    id: "spicejet",
    name: "SpiceJet",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 321 0149",
    whatsapp: "+91 124 4983410",
    websiteUrl: "https://www.spicejet.com",
    notes: "",
  },
  {
    id: "pia",
    name: "Pakistan International Airlines",
    hub: "DXB",
    status: "operating",
    statusLabel: "",
    phone: "+971 4 229 6100",
    whatsapp: "+92 21 111 786 786",
    websiteUrl: "https://www.piac.com.pk",
    notes: "",
  },
];

export const emergencyNumbers: EmergencyNumber[] = [
  {
    name: "Police / Fire / Ambulance (UAE)",
    number: "999",
    description: "General emergency — any UAE emirate",
  },
  {
    name: "Ambulance (Dubai)",
    number: "998",
    description: "Medical emergencies only",
  },
  {
    name: "Civil Defense / Fire",
    number: "997",
    description: "Fire and rescue services",
  },
  {
    name: "Coast Guard",
    number: "996",
    description: "Maritime emergencies",
  },
  {
    name: "Electricity / Water Emergency",
    number: "991",
    description: "DEWA emergency line",
  },
  {
    name: "Dubai Police Tourist Security",
    number: "901",
    description: "Tourist safety and security assistance",
  },
  {
    name: "UAE Government Helpline",
    number: "800-4357",
    description: "24/7 coordination center for stranded travelers",
  },
];

// ─── Embassy & Consulate Contacts ───
export const embassyContacts: EmbassyContact[] = [
  {
    country: "United States",
    countryCode: "US",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 414 2200",
    description: "24/7 Emergency Line",
    website: "https://ae.usembassy.gov",
  },
  {
    country: "United States",
    countryCode: "US",
    name: "Consulate Dubai",
    phone: "+971 4 309 4000",
    description: "24/7 Emergency Line",
    website: "https://ae.usembassy.gov",
  },
  {
    country: "United Kingdom",
    countryCode: "GB",
    name: "Consular Assistance (UAE-wide)",
    phone: "+971 4 309 4444",
    description: "24/7 Consular Assistance",
    website: "https://www.gov.uk/world/united-arab-emirates",
  },
  {
    country: "India",
    countryCode: "IN",
    name: "PBSK Helpline (UAE-wide)",
    phone: "800 46342",
    description: "Toll-free PBSK Helpline",
    website: "https://www.cgidubai.gov.in",
  },
  {
    country: "India",
    countryCode: "IN",
    name: "Official WhatsApp Helpline",
    phone: "+971 54 309 0571",
    description: "Official WhatsApp Helpline",
  },
  {
    country: "India",
    countryCode: "IN",
    name: "Emergency Dubai",
    phone: "+971 50 734 7676",
    description: "Emergency (Death cases only)",
  },
  {
    country: "Pakistan",
    countryCode: "PK",
    name: "Embassy Abu Dhabi",
    phone: "+971 50 124 8934",
    description: "Emergency WhatsApp/Mobile",
    website: "https://pakistanconsulatedubai.ae/",
  },
  {
    country: "Pakistan",
    countryCode: "PK",
    name: "Consulate Dubai",
    phone: "+971 4 397 0612",
    description: "24/7 Emergency Line",
  },
  {
    country: "Philippines",
    countryCode: "PH",
    name: "Embassy Abu Dhabi",
    phone: "+971 50 813 7836",
    description: "Duty Phone and WhatsApp",
    website: "https://dubaipcg.dfa.gov.ph/",
  },
  {
    country: "Philippines",
    countryCode: "PH",
    name: "Consulate Dubai",
    phone: "+971 56 501 5756",
    description: "Duty Phone and WhatsApp",
  },
  {
    country: "Canada",
    countryCode: "CA",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 694 0300",
    description: "24/7 Emergency Line",
    website: "https://travel.gc.ca/assistance/embassies-consulates/united-arab-emirates",
  },
  {
    country: "Canada",
    countryCode: "CA",
    name: "Consulate Dubai",
    phone: "+971 4 404 8444",
    description: "24/7 Emergency Line",
  },
  {
    country: "Australia",
    countryCode: "AU",
    name: "Consulate Dubai",
    phone: "+971 4 508 7100",
    description: "Consular Assistance",
    website: "https://www.dfat.gov.au/about-us/our-locations/missions/Pages/australian-consulate-general-in-dubai-united-arab-emirates",
  },
  {
    country: "Australia",
    countryCode: "AU",
    name: "Global Emergency",
    phone: "+61 2 6261 3305",
    description: "24hr Emergency (Can call collect)",
  },
  {
    country: "Germany",
    countryCode: "DE",
    name: "Consulate Dubai",
    phone: "+971 4 349 8888",
    description: "24/7 Emergency Support",
    website: "https://uae.diplo.de/ae-en/ueber-uns/generalkonsulat1",
  },
  {
    country: "France",
    countryCode: "FR",
    name: "Consulate Dubai",
    phone: "+971 4 408 4900",
    emergencyPhone: "+971 50 644 68 60",
    description: "After-hours emergency support available",
    website: "https://ae.diplomatie.gouv.fr/en",
  },
  {
    country: "South Africa",
    countryCode: "ZA",
    name: "Consulate Dubai",
    phone: "+971 4 397 5222",
    emergencyPhone: "+971 50 558 1235",
    description: "Emergency support",
  },
  {
    country: "South Africa",
    countryCode: "ZA",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 639 0693",
    emergencyPhone: "+971 50 622 4291",
    description: "Emergency support",
  },
  {
    country: "Russia",
    countryCode: "RU",
    name: "Consulate Dubai",
    phone: "+971 4 328 5347",
    emergencyPhone: "+971 50 454 7754",
    description: "Emergency support",
  },
  {
    country: "Kenya",
    countryCode: "KE",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 666 6300",
    emergencyPhone: "+971 54 220 8646",
    description: "WhatsApp emergency support",
  },
  {
    country: "Kenya",
    countryCode: "KE",
    name: "Consulate Dubai",
    phone: "+971 4 398 5888",
    emergencyPhone: "+971 55 671 0900",
    description: "Emergency support",
  },
  {
    country: "Nepal",
    countryCode: "NP",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 631 7600",
    emergencyPhone: "+971 50 394 9304",
    description: "Emergency support",
  },
  {
    country: "Sri Lanka",
    countryCode: "LK",
    name: "Consulate Dubai",
    phone: "+971 4 611 5555",
    generalPhone: "+971 4 611 5533",
    description: "Labour and welfare support line available",
  },
  {
    country: "Bangladesh",
    countryCode: "BD",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 634 5560",
    emergencyPhone: "+971 56 611 7215",
    description: "Emergency support",
  },
  {
    country: "Bangladesh",
    countryCode: "BD",
    name: "Consulate Dubai",
    phone: "+971 4 234 6100",
    emergencyPhone: "+971 56 795 6079",
    description: "Emergency support",
  },
  {
    country: "China",
    countryCode: "CN",
    name: "Consulate Dubai",
    phone: "+971 4 394 4733",
    description: "24/7 Protection Line",
    website: "https://dubai.china-consulate.gov.cn/eng/",
  },
  {
    country: "China",
    countryCode: "CN",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 443 4276",
    description: "Consular Protection Line",
  },
  {
    country: "Japan",
    countryCode: "JP",
    name: "Consulate Dubai",
    phone: "+971 4 293 8888",
    description: "General/Emergency Inquiries",
  },
  {
    country: "South Korea",
    countryCode: "KR",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 441 1520",
    generalPhone: "+971 2 641 6406",
    description: "Consular support line available",
  },
  {
    country: "South Korea",
    countryCode: "KR",
    name: "Consulate Dubai",
    phone: "+971 4 344 9200",
    description: "General Consular Inquiries",
  },
  {
    country: "Egypt",
    countryCode: "EG",
    name: "Consulate Dubai",
    phone: "+971 4 397 1122",
    description: "Consular/Emergency Assistance",
  },
  {
    country: "Jordan",
    countryCode: "JO",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 509 9000",
    description: "Consular Services",
  },
  {
    country: "Lebanon",
    countryCode: "LB",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 445 8000",
    description: "General/Emergency Services",
  },
  {
    country: "Iran",
    countryCode: "IR",
    name: "Consulate Dubai",
    phone: "+971 4 344 4717",
    description: "Consular Assistance",
  },
  {
    country: "Nigeria",
    countryCode: "NG",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 443 1503",
    description: "General Mission Line",
  },
  {
    country: "Nigeria",
    countryCode: "NG",
    name: "Consulate Dubai",
    phone: "+971 4 352 2505",
    description: "Citizen Helpdesk",
  },
  {
    country: "Ethiopia",
    countryCode: "ET",
    name: "Embassy Abu Dhabi",
    phone: "+971 2 665 5111",
    description: "General Inquiries",
  },
  {
    country: "Ethiopia",
    countryCode: "ET",
    name: "Consulate Dubai",
    phone: "+971 4 269 9111",
    description: "General Inquiries",
  },
];

export const verifiedSources: VerifiedSource[] = [
  {
    name: "UAE GCAA",
    type: "Government Authority",
    url: "https://www.gcaa.gov.ae",
    description: "For airspace status, flight restrictions, and official NOTAMs.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.gcaa.gov.ae" },
      { platform: "x", label: "Official X", url: "https://twitter.com/gcaauae" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/gcaauae" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/GCAAUAE" },
      { platform: "youtube", label: "YouTube", url: "https://www.youtube.com/user/gcaauae/videos" },
      {
        platform: "linkedin",
        label: "LinkedIn",
        url: "https://www.linkedin.com/company/general-civil-aviation-authority-gcaa-",
      },
    ],
  },
  {
    name: "WAM (Emirates News Agency)",
    type: "Government Media",
    url: "https://www.wam.ae",
    description: "For official government announcements, visa updates, and policy decisions.",
    channels: [{ platform: "website", label: "Official Website", url: "https://www.wam.ae" }],
  },
  {
    name: "Dubai Airports",
    type: "Airport Operator",
    url: "https://www.dubaiairports.ae",
    description: "For DXB and DWC terminal status, passenger services, and airport operations.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.dubaiairports.ae" },
      { platform: "x", label: "Official X", url: "https://twitter.com/DXB" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/dxb" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/DXB" },
      { platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/company/dubaiairports/" },
    ],
  },
  {
    name: "Abu Dhabi Airports",
    type: "Airport Operator",
    url: "https://www.abudhabiairport.ae",
    description: "For AUH terminal status, flight operations, and passenger updates.",
    channels: [{ platform: "website", label: "Official Website", url: "https://www.abudhabiairport.ae" }],
  },
  {
    name: "The National",
    type: "Verified News",
    url: "https://www.thenationalnews.com",
    description: "For UAE-focused crisis coverage, airline updates, and travel advisories.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.thenationalnews.com" },
      { platform: "x", label: "Official X", url: "https://x.com/TheNationalNews" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/TheNationalNews.com" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/TheNationalNews" },
      { platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/company/thenationalnews" },
      { platform: "youtube", label: "YouTube", url: "https://www.youtube.com/TheNationalNewspaper" },
    ],
  },
  {
    name: "Gulf News",
    type: "Verified News",
    url: "https://www.gulfnews.com",
    description: "For local UAE news, airport disruption reports, and traveler guidance.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.gulfnews.com" },
      { platform: "x", label: "Official X", url: "https://x.com/gulf_news" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/gulfnews" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/GulfNews.UAE" },
      { platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/company/gulf-news" },
      { platform: "youtube", label: "YouTube", url: "https://www.youtube.com/GulfNewsTV" },
      { platform: "telegram", label: "Telegram", url: "https://t.me/gulfnewsUAE" },
    ],
  },
  {
    name: "Al Jazeera",
    type: "Verified News",
    url: "https://www.aljazeera.com",
    description: "For regional geopolitical context and international coverage of the crisis.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.aljazeera.com" },
      { platform: "x", label: "Official X", url: "https://twitter.com/ajenglish" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/aljazeeraenglish/" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/aljazeera" },
      { platform: "youtube", label: "YouTube", url: "https://www.youtube.com/aljazeeraenglish" },
    ],
  },
  {
    name: "Euronews",
    type: "Verified News",
    url: "https://www.euronews.com",
    description: "For European traveler impact, repatriation updates, and global perspective.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.euronews.com" },
      { platform: "x", label: "Official X", url: "https://twitter.com/euronews" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/euronews.tv" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/euronews" },
      { platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/company/euronews" },
      { platform: "youtube", label: "YouTube", url: "https://www.youtube.com/euronews" },
    ],
  },
  {
    name: "CNBC",
    type: "Verified News",
    url: "https://www.cnbc.com",
    description: "For economic impact, insurance guidance, and business travel disruptions.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.cnbc.com" },
      { platform: "x", label: "Official X", url: "https://twitter.com/cnbc" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/cnbc" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/cnbc" },
      { platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/company/cnbc" },
      { platform: "youtube", label: "YouTube", url: "https://www.youtube.com/cnbc" },
    ],
  },
  {
    name: "FlightAware",
    type: "Flight Tracking",
    url: "https://www.flightaware.com",
    description: "For live flight tracking, delay data, and airport departure/arrival boards.",
    channels: [
      { platform: "website", label: "Official Website", url: "https://www.flightaware.com" },
      { platform: "x", label: "Official X", url: "https://twitter.com/flightaware" },
      { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/flightaware" },
      { platform: "facebook", label: "Facebook", url: "https://www.facebook.com/FlightAware" },
      { platform: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/company/flightaware" },
    ],
  },
];
